// Modern CV Templates - Fabric.js JSON format
// Professional, fluid, and modern designs

// TEMPLATE_PROFESSIONAL: Clean modern layout with subtle gradients
export const TEMPLATE_PROFESSIONAL = {
  version: '5.3.0',
  objects: [
    // Header with blue gradient effect (using solid color)
    {
      type: 'rect',
      left: 0,
      top: 0,
      width: 595,
      height: 120,
      fill: '#2563eb',
      selectable: false,
    },
    // Decorative circles
    {
      type: 'circle',
      left: 450,
      top: 20,
      radius: 50,
      fill: '#ffffff',
      opacity: 0.1,
      selectable: false,
    },
    {
      type: 'circle',
      left: 480,
      top: 50,
      radius: 30,
      fill: '#ffffff',
      opacity: 0.15,
      selectable: false,
    },
    // Name
    {
      type: 'i-text',
      left: 50,
      top: 40,
      text: 'SOPHIE',
      fontSize: 36,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 50,
      top: 80,
      text: 'MARTINEZ',
      fontSize: 36,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'left',
      letterSpacing: 1,
    },
    // Title
    {
      type: 'i-text',
      left: 50,
      top: 130,
      text: 'Senior Product Designer',
      fontSize: 16,
      fontFamily: 'Inter',
      fill: '#2563eb',
      textAlign: 'left',
      fontWeight: '600',
    },
    // Contact info
    {
      type: 'i-text',
      left: 50,
      top: 160,
      text: 'sophie.martinez@email.com • +41 79 XXX XX XX • Zurich, Switzerland',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#6B7280',
      textAlign: 'left',
    },
    // Summary section
    {
      type: 'i-text',
      left: 50,
      top: 210,
      text: 'PROFESSIONAL SUMMARY',
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
      letterSpacing: 0.5,
    },
    {
      type: 'rect',
      left: 50,
      top: 235,
      width: 80,
      height: 3,
      fill: '#2563eb',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 250,
      text: 'Experienced product designer with 8+ years creating user-centered digital experiences. Expert in design systems, user research, and cross-functional collaboration. Passionate about building products that solve real problems.',
      fontSize: 11,
      fontFamily: 'Inter',
      fill: '#374151',
      textAlign: 'left',
      width: 495,
      lineHeight: 1.7,
    },
    // Experience
    {
      type: 'i-text',
      left: 50,
      top: 340,
      text: 'EXPERIENCE',
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
      letterSpacing: 0.5,
    },
    {
      type: 'rect',
      left: 50,
      top: 365,
      width: 80,
      height: 3,
      fill: '#2563eb',
      selectable: false,
    },
    // Experience item 1
    {
      type: 'i-text',
      left: 50,
      top: 385,
      text: 'Senior Product Designer',
      fontSize: 13,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 405,
      text: 'Tech Innovations AG • Zurich, Switzerland',
      fontSize: 11,
      fontFamily: 'Inter',
      fill: '#2563eb',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 385,
      text: '2020 - Present',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#9CA3AF',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 70,
      top: 430,
      text: '• Led design of mobile app with 2M+ active users\n• Established design system used across 5 products\n• Increased user engagement by 45% through UX improvements',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#4B5563',
      textAlign: 'left',
      width: 475,
      lineHeight: 1.6,
    },
    // Experience item 2
    {
      type: 'i-text',
      left: 50,
      top: 520,
      text: 'Product Designer',
      fontSize: 13,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 540,
      text: 'StartupHub GmbH • Basel, Switzerland',
      fontSize: 11,
      fontFamily: 'Inter',
      fill: '#2563eb',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 520,
      text: '2018 - 2020',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#9CA3AF',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 70,
      top: 565,
      text: '• Designed and launched 3 major product features\n• Conducted user research with 50+ participants\n• Collaborated with engineering team in agile environment',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#4B5563',
      textAlign: 'left',
      width: 475,
      lineHeight: 1.6,
    },
    // Skills
    {
      type: 'i-text',
      left: 50,
      top: 660,
      text: 'SKILLS',
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
      letterSpacing: 0.5,
    },
    {
      type: 'rect',
      left: 50,
      top: 685,
      width: 80,
      height: 3,
      fill: '#2563eb',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 700,
      text: 'Figma • Sketch • Adobe Creative Suite • Prototyping • User Research • Design Systems • HTML/CSS',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#4B5563',
      textAlign: 'left',
    },
    // Education
    {
      type: 'i-text',
      left: 50,
      top: 750,
      text: 'EDUCATION',
      fontSize: 14,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
      letterSpacing: 0.5,
    },
    {
      type: 'rect',
      left: 50,
      top: 775,
      width: 80,
      height: 3,
      fill: '#2563eb',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 790,
      text: 'Master of Design',
      fontSize: 12,
      fontFamily: 'Inter',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 810,
      text: 'Zurich University of the Arts | 2014 - 2016',
      fontSize: 10,
      fontFamily: 'Inter',
      fill: '#6B7280',
      textAlign: 'left',
    },
  ],
  background: '#ffffff',
}

// TEMPLATE_MINIMAL: Ultra-clean minimalist design
export const TEMPLATE_MINIMAL = {
  version: '5.3.0',
  objects: [
    // Name section
    {
      type: 'i-text',
      left: 50,
      top: 50,
      text: 'ALEXANDER',
      fontSize: 42,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
      letterSpacing: -1,
    },
    {
      type: 'i-text',
      left: 50,
      top: 95,
      text: 'KLEIN',
      fontSize: 42,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
      letterSpacing: -1,
    },
    {
      type: 'rect',
      left: 50,
      top: 145,
      width: 100,
      height: 1,
      fill: '#000000',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 160,
      text: 'Software Engineer',
      fontSize: 14,
      fontFamily: 'Helvetica',
      fill: '#666666',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 185,
      text: 'alexander.klein@email.com',
      fontSize: 10,
      fontFamily: 'Helvetica',
      fill: '#999999',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 205,
      text: '+41 79 XXX XX XX',
      fontSize: 10,
      fontFamily: 'Helvetica',
      fill: '#999999',
      textAlign: 'left',
    },
    // Experience
    {
      type: 'i-text',
      left: 50,
      top: 260,
      text: 'EXPERIENCE',
      fontSize: 11,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
      letterSpacing: 2,
    },
    {
      type: 'i-text',
      left: 50,
      top: 290,
      text: 'Senior Software Engineer',
      fontSize: 12,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 310,
      text: 'SwissTech Solutions AG',
      fontSize: 10,
      fontFamily: 'Helvetica',
      fill: '#666666',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 290,
      text: '2020 - Present',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#999999',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 50,
      top: 335,
      text: 'Led development of microservices architecture handling 5M+ requests daily. Built scalable React applications with 60% performance improvement.',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#333333',
      textAlign: 'left',
      width: 495,
      lineHeight: 1.6,
    },
    {
      type: 'i-text',
      left: 50,
      top: 400,
      text: 'Software Engineer',
      fontSize: 12,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 420,
      text: 'TechStart GmbH',
      fontSize: 10,
      fontFamily: 'Helvetica',
      fill: '#666666',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 400,
      text: '2018 - 2020',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#999999',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 50,
      top: 445,
      text: 'Developed RESTful APIs using Node.js. Created responsive UIs with React and TypeScript.',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#333333',
      textAlign: 'left',
      width: 495,
      lineHeight: 1.6,
    },
    // Skills
    {
      type: 'i-text',
      left: 50,
      top: 520,
      text: 'SKILLS',
      fontSize: 11,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
      letterSpacing: 2,
    },
    {
      type: 'i-text',
      left: 50,
      top: 550,
      text: 'React • TypeScript • Node.js • Python • AWS • Docker • Kubernetes',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#333333',
      textAlign: 'left',
    },
    // Education
    {
      type: 'i-text',
      left: 50,
      top: 600,
      text: 'EDUCATION',
      fontSize: 11,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
      letterSpacing: 2,
    },
    {
      type: 'i-text',
      left: 50,
      top: 630,
      text: 'B.S. Computer Science',
      fontSize: 12,
      fontFamily: 'Helvetica',
      fontWeight: 'bold',
      fill: '#000000',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 650,
      text: 'ETH Zurich | 2014 - 2018',
      fontSize: 9,
      fontFamily: 'Helvetica',
      fill: '#666666',
      textAlign: 'left',
    },
  ],
  background: '#ffffff',
}

// TEMPLATE_CONTEMPORARY: Modern contemporary design with accent colors
export const TEMPLATE_CONTEMPORARY = {
  version: '5.3.0',
  objects: [
    // Left accent bar
    {
      type: 'rect',
      left: 0,
      top: 0,
      width: 8,
      height: 842,
      fill: '#10B981',
      selectable: false,
    },
    // Header section
    {
      type: 'i-text',
      left: 30,
      top: 50,
      text: 'MARIA',
      fontSize: 38,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 30,
      top: 95,
      text: 'SCHMIDT',
      fontSize: 38,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 30,
      top: 145,
      text: 'Marketing Director',
      fontSize: 16,
      fontFamily: 'Roboto',
      fill: '#10B981',
      textAlign: 'left',
      fontWeight: '600',
    },
    {
      type: 'i-text',
      left: 30,
      top: 175,
      text: 'maria.schmidt@email.com • +41 79 XXX XX XX • Bern, Switzerland',
      fontSize: 10,
      fontFamily: 'Roboto',
      fill: '#6B7280',
      textAlign: 'left',
    },
    // Summary
    {
      type: 'i-text',
      left: 30,
      top: 230,
      text: 'ABOUT',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#10B981',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 30,
      top: 255,
      text: 'Strategic marketing leader with 10+ years of experience driving brand growth and digital transformation. Expert in brand strategy, digital campaigns, and team leadership.',
      fontSize: 10,
      fontFamily: 'Roboto',
      fill: '#374151',
      textAlign: 'left',
      width: 535,
      lineHeight: 1.7,
    },
    // Experience
    {
      type: 'i-text',
      left: 30,
      top: 330,
      text: 'EXPERIENCE',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#10B981',
      textAlign: 'left',
      letterSpacing: 1,
    },
    // Experience item with colored dot
    {
      type: 'circle',
      left: 30,
      top: 360,
      radius: 4,
      fill: '#10B981',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 355,
      text: 'Marketing Director',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 375,
      text: 'Brand Agency AG • Bern, Switzerland',
      fontSize: 10,
      fontFamily: 'Roboto',
      fill: '#6B7280',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 355,
      text: '2019 - Present',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#9CA3AF',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 50,
      top: 400,
      text: '• Launched 15+ successful campaigns increasing brand awareness by 250%\n• Managed team of 12 marketing professionals\n• Increased digital revenue by 180%',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#4B5563',
      textAlign: 'left',
      width: 515,
      lineHeight: 1.6,
    },
    {
      type: 'circle',
      left: 30,
      top: 480,
      radius: 4,
      fill: '#10B981',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 475,
      text: 'Senior Marketing Manager',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 495,
      text: 'Digital Solutions GmbH • Zurich, Switzerland',
      fontSize: 10,
      fontFamily: 'Roboto',
      fill: '#6B7280',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 475,
      text: '2016 - 2019',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#9CA3AF',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 50,
      top: 520,
      text: '• Developed comprehensive digital marketing strategies\n• Increased lead generation by 120%\n• Managed annual marketing budget of $3M+',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#4B5563',
      textAlign: 'left',
      width: 515,
      lineHeight: 1.6,
    },
    // Skills
    {
      type: 'i-text',
      left: 30,
      top: 600,
      text: 'SKILLS',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#10B981',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 30,
      top: 630,
      text: 'Brand Strategy • Digital Marketing • Social Media • Analytics • Team Leadership • Content Creation',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#4B5563',
      textAlign: 'left',
    },
    // Education
    {
      type: 'i-text',
      left: 30,
      top: 680,
      text: 'EDUCATION',
      fontSize: 13,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#10B981',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 30,
      top: 710,
      text: 'Master of Business Administration',
      fontSize: 11,
      fontFamily: 'Roboto',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 30,
      top: 730,
      text: 'University of St. Gallen | 2012 - 2014',
      fontSize: 9,
      fontFamily: 'Roboto',
      fill: '#6B7280',
      textAlign: 'left',
    },
  ],
  background: '#ffffff',
}

// TEMPLATE_EXECUTIVE: Professional executive design
export const TEMPLATE_EXECUTIVE = {
  version: '5.3.0',
  objects: [
    // Top border
    {
      type: 'rect',
      left: 0,
      top: 0,
      width: 595,
      height: 6,
      fill: '#1E40AF',
      selectable: false,
    },
    // Name section
    {
      type: 'i-text',
      left: 50,
      top: 40,
      text: 'THOMAS',
      fontSize: 40,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 2,
    },
    {
      type: 'i-text',
      left: 50,
      top: 85,
      text: 'WEBER',
      fontSize: 40,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 2,
    },
    {
      type: 'rect',
      left: 50,
      top: 130,
      width: 120,
      height: 2,
      fill: '#1E40AF',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 50,
      top: 145,
      text: 'Chief Executive Officer',
      fontSize: 15,
      fontFamily: 'Georgia',
      fill: '#4B5563',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 170,
      text: 'thomas.weber@email.com | +41 79 XXX XX XX | Geneva, Switzerland',
      fontSize: 10,
      fontFamily: 'Georgia',
      fill: '#6B7280',
      textAlign: 'left',
    },
    // Summary
    {
      type: 'i-text',
      left: 50,
      top: 220,
      text: 'EXECUTIVE SUMMARY',
      fontSize: 13,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 50,
      top: 245,
      text: 'Visionary leader with 15+ years of executive experience driving organizational growth and transformation. Proven track record of scaling businesses from startup to enterprise level, achieving $500M+ valuations.',
      fontSize: 10,
      fontFamily: 'Georgia',
      fill: '#2A2A2A',
      textAlign: 'left',
      width: 495,
      lineHeight: 1.7,
    },
    // Experience
    {
      type: 'i-text',
      left: 50,
      top: 320,
      text: 'PROFESSIONAL EXPERIENCE',
      fontSize: 13,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 50,
      top: 350,
      text: 'Chief Executive Officer',
      fontSize: 13,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 370,
      text: 'Global Corporation AG',
      fontSize: 11,
      fontFamily: 'Georgia',
      fontStyle: 'italic',
      fill: '#4B5563',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 450,
      top: 350,
      text: '2018 - Present',
      fontSize: 10,
      fontFamily: 'Georgia',
      fill: '#6B7280',
      textAlign: 'right',
    },
    {
      type: 'i-text',
      left: 70,
      top: 395,
      text: '• Led company through IPO, achieving $500M valuation\n• Increased revenue by 300% over 5 years\n• Expanded operations to 15 countries worldwide',
      fontSize: 9,
      fontFamily: 'Georgia',
      fill: '#2A2A2A',
      textAlign: 'left',
      width: 475,
      lineHeight: 1.6,
    },
    // Education
    {
      type: 'i-text',
      left: 50,
      top: 480,
      text: 'EDUCATION',
      fontSize: 13,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 50,
      top: 510,
      text: 'Master of Business Administration',
      fontSize: 12,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#111827',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 535,
      text: 'University of St. Gallen | 2005 - 2007',
      fontSize: 10,
      fontFamily: 'Georgia',
      fill: '#6B7280',
      textAlign: 'left',
    },
    // Achievements
    {
      type: 'i-text',
      left: 50,
      top: 600,
      text: 'KEY ACHIEVEMENTS',
      fontSize: 13,
      fontFamily: 'Georgia',
      fontWeight: 'bold',
      fill: '#1E40AF',
      textAlign: 'left',
      letterSpacing: 1,
    },
    {
      type: 'i-text',
      left: 70,
      top: 630,
      text: '• Fortune 500 CEO of the Year 2022\n• Led acquisition of 3 major competitors\n• Established company as industry leader in European market',
      fontSize: 9,
      fontFamily: 'Georgia',
      fill: '#2A2A2A',
      textAlign: 'left',
      width: 475,
      lineHeight: 1.6,
    },
  ],
  background: '#ffffff',
}

// TEMPLATE_TECH: Modern tech-focused design
export const TEMPLATE_TECH = {
  version: '5.3.0',
  objects: [
    // Top accent
    {
      type: 'rect',
      left: 0,
      top: 0,
      width: 595,
      height: 6,
      fill: '#3B82F6',
      selectable: false,
    },
    // Name
    {
      type: 'i-text',
      left: 50,
      top: 40,
      text: 'DAVID',
      fontSize: 38,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 85,
      text: 'MULLER',
      fontSize: 38,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 135,
      text: 'Full Stack Developer',
      fontSize: 15,
      fontFamily: 'Courier New',
      fill: '#1F2937',
      textAlign: 'left',
    },
    // Contact in code style
    {
      type: 'rect',
      left: 50,
      top: 165,
      width: 495,
      height: 50,
      fill: '#F3F4F6',
      rx: 4,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 60,
      top: 175,
      text: 'const contact = {',
      fontSize: 9,
      fontFamily: 'Courier New',
      fill: '#6B7280',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 60,
      top: 190,
      text: '  email: "david.muller@email.com",',
      fontSize: 9,
      fontFamily: 'Courier New',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 60,
      top: 205,
      text: '  phone: "+41 79 XXX XX XX",',
      fontSize: 9,
      fontFamily: 'Courier New',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    // Skills as tags
    {
      type: 'i-text',
      left: 50,
      top: 250,
      text: 'SKILLS',
      fontSize: 14,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#1F2937',
      textAlign: 'left',
    },
    {
      type: 'rect',
      left: 50,
      top: 280,
      width: 70,
      height: 25,
      fill: '#3B82F6',
      rx: 3,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 85,
      top: 287,
      text: 'React',
      fontSize: 9,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    {
      type: 'rect',
      left: 130,
      top: 280,
      width: 70,
      height: 25,
      fill: '#3B82F6',
      rx: 3,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 165,
      top: 287,
      text: 'Node.js',
      fontSize: 9,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    {
      type: 'rect',
      left: 210,
      top: 280,
      width: 80,
      height: 25,
      fill: '#3B82F6',
      rx: 3,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 250,
      top: 287,
      text: 'TypeScript',
      fontSize: 9,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    {
      type: 'rect',
      left: 300,
      top: 280,
      width: 70,
      height: 25,
      fill: '#3B82F6',
      rx: 3,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 335,
      top: 287,
      text: 'AWS',
      fontSize: 9,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    // Experience
    {
      type: 'i-text',
      left: 50,
      top: 350,
      text: 'EXPERIENCE',
      fontSize: 14,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#1F2937',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 380,
      text: '> Senior Developer',
      fontSize: 12,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 405,
      text: 'Tech Innovations AG | 2020 - Present',
      fontSize: 10,
      fontFamily: 'Courier New',
      fill: '#6B7280',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 70,
      top: 430,
      text: '• Built scalable microservices architecture handling 5M+ requests daily\n• Led team of 5 developers\n• Reduced API response time by 60%',
      fontSize: 9,
      fontFamily: 'Courier New',
      fill: '#1F2937',
      textAlign: 'left',
      width: 475,
      lineHeight: 1.6,
    },
    // Education
    {
      type: 'i-text',
      left: 50,
      top: 550,
      text: 'EDUCATION',
      fontSize: 14,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#1F2937',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 580,
      text: '> B.S. Computer Science',
      fontSize: 12,
      fontFamily: 'Courier New',
      fontWeight: 'bold',
      fill: '#3B82F6',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 605,
      text: 'ETH Zurich | 2016 - 2020',
      fontSize: 10,
      fontFamily: 'Courier New',
      fill: '#6B7280',
      textAlign: 'left',
    },
  ],
  background: '#ffffff',
}

// TEMPLATE_CREATIVE: Bold creative design
export const TEMPLATE_CREATIVE = {
  version: '5.3.0',
  objects: [
    // Colorful header
    {
      type: 'rect',
      left: 0,
      top: 0,
      width: 595,
      height: 140,
      fill: '#10b981',
      selectable: false,
    },
    {
      type: 'circle',
      left: 450,
      top: 20,
      radius: 60,
      fill: '#A78BFA',
      opacity: 0.4,
      selectable: false,
    },
    {
      type: 'circle',
      left: 480,
      top: 50,
      radius: 40,
      fill: '#C4B5FD',
      opacity: 0.5,
      selectable: false,
    },
    // Name
    {
      type: 'i-text',
      left: 50,
      top: 50,
      text: 'SOPHIA',
      fontSize: 40,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 95,
      text: 'ANDERSON',
      fontSize: 40,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 150,
      text: 'Creative Director',
      fontSize: 16,
      fontFamily: 'Arial',
      fill: '#E0E7FF',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 180,
      text: 'sophia.anderson@email.com • +41 79 XXX XX XX • Lausanne, Switzerland',
      fontSize: 10,
      fontFamily: 'Arial',
      fill: '#C7D2FE',
      textAlign: 'left',
    },
    // About
    {
      type: 'i-text',
      left: 50,
      top: 240,
      text: 'ABOUT',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#10b981',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 270,
      text: 'Passionate creative director with 8+ years of experience leading design teams and delivering award-winning campaigns. Expert in brand strategy, visual design, and team leadership.',
      fontSize: 11,
      fontFamily: 'Arial',
      fill: '#1F2937',
      textAlign: 'left',
      width: 495,
      lineHeight: 1.7,
    },
    // Experience with colored accents
    {
      type: 'i-text',
      left: 50,
      top: 350,
      text: 'EXPERIENCE',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#10b981',
      textAlign: 'left',
    },
    {
      type: 'rect',
      left: 50,
      top: 385,
      width: 4,
      height: 70,
      fill: '#10b981',
      selectable: false,
    },
    {
      type: 'i-text',
      left: 65,
      top: 390,
      text: 'Creative Director',
      fontSize: 14,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#1F2937',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 65,
      top: 415,
      text: 'Agency Name AG | 2018 - Present',
      fontSize: 11,
      fontFamily: 'Arial',
      fill: '#6B7280',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 65,
      top: 440,
      text: 'Led creative vision for Fortune 500 clients. Increased brand awareness by 300%.',
      fontSize: 10,
      fontFamily: 'Arial',
      fill: '#374151',
      textAlign: 'left',
      width: 480,
      lineHeight: 1.6,
    },
    // Skills as colored boxes
    {
      type: 'i-text',
      left: 50,
      top: 520,
      text: 'SKILLS',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#10b981',
      textAlign: 'left',
    },
    {
      type: 'rect',
      left: 50,
      top: 555,
      width: 90,
      height: 30,
      fill: '#10b981',
      rx: 4,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 95,
      top: 562,
      text: 'Branding',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    {
      type: 'rect',
      left: 150,
      top: 555,
      width: 90,
      height: 30,
      fill: '#A78BFA',
      rx: 4,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 195,
      top: 562,
      text: 'Strategy',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    {
      type: 'rect',
      left: 250,
      top: 555,
      width: 90,
      height: 30,
      fill: '#C4B5FD',
      rx: 4,
      selectable: false,
    },
    {
      type: 'i-text',
      left: 295,
      top: 562,
      text: 'Design',
      fontSize: 10,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#ffffff',
      textAlign: 'center',
    },
    // Education
    {
      type: 'i-text',
      left: 50,
      top: 640,
      text: 'EDUCATION',
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#10b981',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 670,
      text: 'Master of Fine Arts',
      fontSize: 13,
      fontFamily: 'Arial',
      fontWeight: 'bold',
      fill: '#1F2937',
      textAlign: 'left',
    },
    {
      type: 'i-text',
      left: 50,
      top: 690,
      text: 'University of the Arts | 2013 - 2015',
      fontSize: 10,
      fontFamily: 'Arial',
      fill: '#6B7280',
      textAlign: 'left',
    },
  ],
  background: '#ffffff',
}

// Helper function to get template JSON
export const getTemplateJSON = (templateName: string): string => {
  switch (templateName) {
    case 'minimalist':
    case 'minimal':
      return JSON.stringify(TEMPLATE_MINIMAL)
    case 'creative':
      return JSON.stringify(TEMPLATE_CREATIVE)
    case 'classic':
    case 'professional':
      return JSON.stringify(TEMPLATE_PROFESSIONAL)
    case 'tech':
      return JSON.stringify(TEMPLATE_TECH)
    case 'executive':
      return JSON.stringify(TEMPLATE_EXECUTIVE)
    case 'colorful':
    case 'contemporary':
      return JSON.stringify(TEMPLATE_CONTEMPORARY)
    case 'modern':
      return JSON.stringify(TEMPLATE_PROFESSIONAL)
    case 'elegant':
      return JSON.stringify(TEMPLATE_EXECUTIVE)
    case 'bold':
      return JSON.stringify(TEMPLATE_CREATIVE)
    default:
      return JSON.stringify(TEMPLATE_PROFESSIONAL)
  }
}

// Get all available templates
export const getAllTemplates = () => [
  { id: 'professional', name: 'Professional', description: 'Modern gradient • Clean & elegant', layout: 'header' },
  { id: 'minimal', name: 'Minimal', description: 'Ultra-clean • Typography-focused', layout: 'header' },
  { id: 'contemporary', name: 'Contemporary', description: 'Green accent • Modern layout', layout: 'sidebar' },
  { id: 'executive', name: 'Executive', description: 'Blue accent • Professional leadership', layout: 'header' },
  { id: 'tech', name: 'Tech', description: 'Code-style • Developer-focused', layout: 'header' },
  { id: 'creative', name: 'Creative', description: 'Green accent • Bold & modern', layout: 'header' },
]
